/**
 * Alfresco Search REST API
 * Provides access to the search features of Alfresco
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.alfresco.client.api.search.model;

import java.util.List;
import java.util.Objects;

import com.alfresco.client.api.common.representation.PaginationRepresentation;
import com.alfresco.client.api.common.representation.ResultPaging;
import com.google.gson.annotations.SerializedName;

/**
 * ResultSetPagingList
 */
public class ResultSetRepresentation<T> extends ResultPaging<T>
{
    @SerializedName("context")
    private ResultSetContext context = null;

    public ResultSetRepresentation(List<T> objects, ResultSetContext context, PaginationRepresentation pagination)
    {
        super(objects, pagination);
        this.context = context;
    }

    /**
     * Get context
     * 
     * @return context
     **/
    public ResultSetContext getContext()
    {
        return context;
    }

    public void setContext(ResultSetContext context)
    {
        this.context = context;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }
        ResultSetRepresentation resultSetPagingList = (ResultSetRepresentation) o;
        return Objects.equals(this.pagination, resultSetPagingList.pagination)
                && Objects.equals(this.context, resultSetPagingList.context)
                && Objects.equals(this.objects, resultSetPagingList.objects);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(pagination, context, objects);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class ResultSetPagingList {\n");

        sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
        sb.append("    context: ").append(toIndentedString(context)).append("\n");
        sb.append("    entries: ").append(toIndentedString(objects)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null) { return "null"; }
        return o.toString().replace("\n", "\n    ");
    }
}
